// Code generated by ent, DO NOT EDIT.

package workunitinfo

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldName, v))
}

// AddressID applies equality check predicate on the "address_id" field. It's identical to AddressIDEQ.
func AddressID(v uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldAddressID, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldImageURL, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldContainsFold(FieldName, v))
}

// AddressIDEQ applies the EQ predicate on the "address_id" field.
func AddressIDEQ(v uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldAddressID, v))
}

// AddressIDNEQ applies the NEQ predicate on the "address_id" field.
func AddressIDNEQ(v uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNEQ(FieldAddressID, v))
}

// AddressIDIn applies the In predicate on the "address_id" field.
func AddressIDIn(vs ...uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldIn(FieldAddressID, vs...))
}

// AddressIDNotIn applies the NotIn predicate on the "address_id" field.
func AddressIDNotIn(vs ...uuid.UUID) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNotIn(FieldAddressID, vs...))
}

// AddressIDIsNil applies the IsNil predicate on the "address_id" field.
func AddressIDIsNil() predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldIsNull(FieldAddressID))
}

// AddressIDNotNil applies the NotNil predicate on the "address_id" field.
func AddressIDNotNil() predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNotNull(FieldAddressID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNotIn(FieldType, vs...))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLIsNil applies the IsNil predicate on the "image_url" field.
func ImageURLIsNil() predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldIsNull(FieldImageURL))
}

// ImageURLNotNil applies the NotNil predicate on the "image_url" field.
func ImageURLNotNil() predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldNotNull(FieldImageURL))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.FieldContainsFold(FieldImageURL, v))
}

// HasAddress applies the HasEdge predicate on the "address" edge.
func HasAddress() predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AddressTable, AddressColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAddressWith applies the HasEdge predicate on the "address" edge with a given conditions (other predicates).
func HasAddressWith(preds ...predicate.Address) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(func(s *sql.Selector) {
		step := newAddressStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkUnitInfo) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkUnitInfo) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkUnitInfo) predicate.WorkUnitInfo {
	return predicate.WorkUnitInfo(sql.NotPredicates(p))
}
