// Code generated by ent, DO NOT EDIT.

package userrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserRole applies equality check predicate on the "user_role" field. It's identical to UserRoleEQ.
func UserRole(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUserRole, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserRoleEQ applies the EQ predicate on the "user_role" field.
func UserRoleEQ(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldEQ(FieldUserRole, v))
}

// UserRoleNEQ applies the NEQ predicate on the "user_role" field.
func UserRoleNEQ(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldNEQ(FieldUserRole, v))
}

// UserRoleIn applies the In predicate on the "user_role" field.
func UserRoleIn(vs ...string) predicate.UserRole {
	return predicate.UserRole(sql.FieldIn(FieldUserRole, vs...))
}

// UserRoleNotIn applies the NotIn predicate on the "user_role" field.
func UserRoleNotIn(vs ...string) predicate.UserRole {
	return predicate.UserRole(sql.FieldNotIn(FieldUserRole, vs...))
}

// UserRoleGT applies the GT predicate on the "user_role" field.
func UserRoleGT(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldGT(FieldUserRole, v))
}

// UserRoleGTE applies the GTE predicate on the "user_role" field.
func UserRoleGTE(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldGTE(FieldUserRole, v))
}

// UserRoleLT applies the LT predicate on the "user_role" field.
func UserRoleLT(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldLT(FieldUserRole, v))
}

// UserRoleLTE applies the LTE predicate on the "user_role" field.
func UserRoleLTE(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldLTE(FieldUserRole, v))
}

// UserRoleContains applies the Contains predicate on the "user_role" field.
func UserRoleContains(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldContains(FieldUserRole, v))
}

// UserRoleHasPrefix applies the HasPrefix predicate on the "user_role" field.
func UserRoleHasPrefix(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldHasPrefix(FieldUserRole, v))
}

// UserRoleHasSuffix applies the HasSuffix predicate on the "user_role" field.
func UserRoleHasSuffix(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldHasSuffix(FieldUserRole, v))
}

// UserRoleEqualFold applies the EqualFold predicate on the "user_role" field.
func UserRoleEqualFold(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldEqualFold(FieldUserRole, v))
}

// UserRoleContainsFold applies the ContainsFold predicate on the "user_role" field.
func UserRoleContainsFold(v string) predicate.UserRole {
	return predicate.UserRole(sql.FieldContainsFold(FieldUserRole, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRole) predicate.UserRole {
	return predicate.UserRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRole) predicate.UserRole {
	return predicate.UserRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRole) predicate.UserRole {
	return predicate.UserRole(sql.NotPredicates(p))
}
