// Code generated by ent, DO NOT EDIT.

package productqty

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkUnitID applies equality check predicate on the "work_unit_id" field. It's identical to WorkUnitIDEQ.
func WorkUnitID(v uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldWorkUnitID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldProductID, v))
}

// ProductColorID applies equality check predicate on the "product_color_id" field. It's identical to ProductColorIDEQ.
func ProductColorID(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldProductColorID, v))
}

// PricePerUnit applies equality check predicate on the "price_per_unit" field. It's identical to PricePerUnitEQ.
func PricePerUnit(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldPricePerUnit, v))
}

// Qty applies equality check predicate on the "qty" field. It's identical to QtyEQ.
func Qty(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldQty, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLTE(FieldUpdatedAt, v))
}

// WorkUnitIDEQ applies the EQ predicate on the "work_unit_id" field.
func WorkUnitIDEQ(v uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldWorkUnitID, v))
}

// WorkUnitIDNEQ applies the NEQ predicate on the "work_unit_id" field.
func WorkUnitIDNEQ(v uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldWorkUnitID, v))
}

// WorkUnitIDIn applies the In predicate on the "work_unit_id" field.
func WorkUnitIDIn(vs ...uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldWorkUnitID, vs...))
}

// WorkUnitIDNotIn applies the NotIn predicate on the "work_unit_id" field.
func WorkUnitIDNotIn(vs ...uuid.UUID) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldWorkUnitID, vs...))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLTE(FieldProductID, v))
}

// ProductIDContains applies the Contains predicate on the "product_id" field.
func ProductIDContains(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldContains(FieldProductID, v))
}

// ProductIDHasPrefix applies the HasPrefix predicate on the "product_id" field.
func ProductIDHasPrefix(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldHasPrefix(FieldProductID, v))
}

// ProductIDHasSuffix applies the HasSuffix predicate on the "product_id" field.
func ProductIDHasSuffix(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldHasSuffix(FieldProductID, v))
}

// ProductIDEqualFold applies the EqualFold predicate on the "product_id" field.
func ProductIDEqualFold(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEqualFold(FieldProductID, v))
}

// ProductIDContainsFold applies the ContainsFold predicate on the "product_id" field.
func ProductIDContainsFold(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldContainsFold(FieldProductID, v))
}

// ProductColorIDEQ applies the EQ predicate on the "product_color_id" field.
func ProductColorIDEQ(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldProductColorID, v))
}

// ProductColorIDNEQ applies the NEQ predicate on the "product_color_id" field.
func ProductColorIDNEQ(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldProductColorID, v))
}

// ProductColorIDIn applies the In predicate on the "product_color_id" field.
func ProductColorIDIn(vs ...string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldProductColorID, vs...))
}

// ProductColorIDNotIn applies the NotIn predicate on the "product_color_id" field.
func ProductColorIDNotIn(vs ...string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldProductColorID, vs...))
}

// ProductColorIDGT applies the GT predicate on the "product_color_id" field.
func ProductColorIDGT(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGT(FieldProductColorID, v))
}

// ProductColorIDGTE applies the GTE predicate on the "product_color_id" field.
func ProductColorIDGTE(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGTE(FieldProductColorID, v))
}

// ProductColorIDLT applies the LT predicate on the "product_color_id" field.
func ProductColorIDLT(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLT(FieldProductColorID, v))
}

// ProductColorIDLTE applies the LTE predicate on the "product_color_id" field.
func ProductColorIDLTE(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLTE(FieldProductColorID, v))
}

// ProductColorIDContains applies the Contains predicate on the "product_color_id" field.
func ProductColorIDContains(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldContains(FieldProductColorID, v))
}

// ProductColorIDHasPrefix applies the HasPrefix predicate on the "product_color_id" field.
func ProductColorIDHasPrefix(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldHasPrefix(FieldProductColorID, v))
}

// ProductColorIDHasSuffix applies the HasSuffix predicate on the "product_color_id" field.
func ProductColorIDHasSuffix(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldHasSuffix(FieldProductColorID, v))
}

// ProductColorIDEqualFold applies the EqualFold predicate on the "product_color_id" field.
func ProductColorIDEqualFold(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEqualFold(FieldProductColorID, v))
}

// ProductColorIDContainsFold applies the ContainsFold predicate on the "product_color_id" field.
func ProductColorIDContainsFold(v string) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldContainsFold(FieldProductColorID, v))
}

// PricePerUnitEQ applies the EQ predicate on the "price_per_unit" field.
func PricePerUnitEQ(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldPricePerUnit, v))
}

// PricePerUnitNEQ applies the NEQ predicate on the "price_per_unit" field.
func PricePerUnitNEQ(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldPricePerUnit, v))
}

// PricePerUnitIn applies the In predicate on the "price_per_unit" field.
func PricePerUnitIn(vs ...decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldPricePerUnit, vs...))
}

// PricePerUnitNotIn applies the NotIn predicate on the "price_per_unit" field.
func PricePerUnitNotIn(vs ...decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldPricePerUnit, vs...))
}

// PricePerUnitGT applies the GT predicate on the "price_per_unit" field.
func PricePerUnitGT(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGT(FieldPricePerUnit, v))
}

// PricePerUnitGTE applies the GTE predicate on the "price_per_unit" field.
func PricePerUnitGTE(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGTE(FieldPricePerUnit, v))
}

// PricePerUnitLT applies the LT predicate on the "price_per_unit" field.
func PricePerUnitLT(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLT(FieldPricePerUnit, v))
}

// PricePerUnitLTE applies the LTE predicate on the "price_per_unit" field.
func PricePerUnitLTE(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLTE(FieldPricePerUnit, v))
}

// QtyEQ applies the EQ predicate on the "qty" field.
func QtyEQ(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldEQ(FieldQty, v))
}

// QtyNEQ applies the NEQ predicate on the "qty" field.
func QtyNEQ(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNEQ(FieldQty, v))
}

// QtyIn applies the In predicate on the "qty" field.
func QtyIn(vs ...decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldIn(FieldQty, vs...))
}

// QtyNotIn applies the NotIn predicate on the "qty" field.
func QtyNotIn(vs ...decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldNotIn(FieldQty, vs...))
}

// QtyGT applies the GT predicate on the "qty" field.
func QtyGT(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGT(FieldQty, v))
}

// QtyGTE applies the GTE predicate on the "qty" field.
func QtyGTE(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldGTE(FieldQty, v))
}

// QtyLT applies the LT predicate on the "qty" field.
func QtyLT(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLT(FieldQty, v))
}

// QtyLTE applies the LTE predicate on the "qty" field.
func QtyLTE(v decimal.Decimal) predicate.ProductQty {
	return predicate.ProductQty(sql.FieldLTE(FieldQty, v))
}

// HasWorkUnit applies the HasEdge predicate on the "work_unit" edge.
func HasWorkUnit() predicate.ProductQty {
	return predicate.ProductQty(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WorkUnitTable, WorkUnitColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkUnitWith applies the HasEdge predicate on the "work_unit" edge with a given conditions (other predicates).
func HasWorkUnitWith(preds ...predicate.WorkUnitInfo) predicate.ProductQty {
	return predicate.ProductQty(func(s *sql.Selector) {
		step := newWorkUnitStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.ProductQty {
	return predicate.ProductQty(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.ProductInfo) predicate.ProductQty {
	return predicate.ProductQty(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProductColor applies the HasEdge predicate on the "product_color" edge.
func HasProductColor() predicate.ProductQty {
	return predicate.ProductQty(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProductColorTable, ProductColorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductColorWith applies the HasEdge predicate on the "product_color" edge with a given conditions (other predicates).
func HasProductColorWith(preds ...predicate.ProductColor) predicate.ProductQty {
	return predicate.ProductQty(func(s *sql.Selector) {
		step := newProductColorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductQty) predicate.ProductQty {
	return predicate.ProductQty(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductQty) predicate.ProductQty {
	return predicate.ProductQty(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductQty) predicate.ProductQty {
	return predicate.ProductQty(sql.NotPredicates(p))
}
