// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thaiha1607/foursquare_server/ent/invoicestatuscode"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
)

// InvoiceStatusCodeDelete is the builder for deleting a InvoiceStatusCode entity.
type InvoiceStatusCodeDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceStatusCodeMutation
}

// Where appends a list predicates to the InvoiceStatusCodeDelete builder.
func (iscd *InvoiceStatusCodeDelete) Where(ps ...predicate.InvoiceStatusCode) *InvoiceStatusCodeDelete {
	iscd.mutation.Where(ps...)
	return iscd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iscd *InvoiceStatusCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, iscd.sqlExec, iscd.mutation, iscd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (iscd *InvoiceStatusCodeDelete) ExecX(ctx context.Context) int {
	n, err := iscd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iscd *InvoiceStatusCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoicestatuscode.Table, sqlgraph.NewFieldSpec(invoicestatuscode.FieldID, field.TypeInt))
	if ps := iscd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, iscd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	iscd.mutation.done = true
	return affected, err
}

// InvoiceStatusCodeDeleteOne is the builder for deleting a single InvoiceStatusCode entity.
type InvoiceStatusCodeDeleteOne struct {
	iscd *InvoiceStatusCodeDelete
}

// Where appends a list predicates to the InvoiceStatusCodeDelete builder.
func (iscdo *InvoiceStatusCodeDeleteOne) Where(ps ...predicate.InvoiceStatusCode) *InvoiceStatusCodeDeleteOne {
	iscdo.iscd.mutation.Where(ps...)
	return iscdo
}

// Exec executes the deletion query.
func (iscdo *InvoiceStatusCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := iscdo.iscd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoicestatuscode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iscdo *InvoiceStatusCodeDeleteOne) ExecX(ctx context.Context) {
	if err := iscdo.Exec(ctx); err != nil {
		panic(err)
	}
}
