// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thaiha1607/foursquare_server/ent/messagetype"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
)

// MessageTypeDelete is the builder for deleting a MessageType entity.
type MessageTypeDelete struct {
	config
	hooks    []Hook
	mutation *MessageTypeMutation
}

// Where appends a list predicates to the MessageTypeDelete builder.
func (mtd *MessageTypeDelete) Where(ps ...predicate.MessageType) *MessageTypeDelete {
	mtd.mutation.Where(ps...)
	return mtd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mtd *MessageTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mtd.sqlExec, mtd.mutation, mtd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mtd *MessageTypeDelete) ExecX(ctx context.Context) int {
	n, err := mtd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mtd *MessageTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(messagetype.Table, sqlgraph.NewFieldSpec(messagetype.FieldID, field.TypeInt))
	if ps := mtd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mtd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mtd.mutation.done = true
	return affected, err
}

// MessageTypeDeleteOne is the builder for deleting a single MessageType entity.
type MessageTypeDeleteOne struct {
	mtd *MessageTypeDelete
}

// Where appends a list predicates to the MessageTypeDelete builder.
func (mtdo *MessageTypeDeleteOne) Where(ps ...predicate.MessageType) *MessageTypeDeleteOne {
	mtdo.mtd.mutation.Where(ps...)
	return mtdo
}

// Exec executes the deletion query.
func (mtdo *MessageTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := mtdo.mtd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{messagetype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mtdo *MessageTypeDeleteOne) ExecX(ctx context.Context) {
	if err := mtdo.Exec(ctx); err != nil {
		panic(err)
	}
}
