// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thaiha1607/foursquare_server/ent/messagetype"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
)

// MessageTypeUpdate is the builder for updating MessageType entities.
type MessageTypeUpdate struct {
	config
	hooks    []Hook
	mutation *MessageTypeMutation
}

// Where appends a list predicates to the MessageTypeUpdate builder.
func (mtu *MessageTypeUpdate) Where(ps ...predicate.MessageType) *MessageTypeUpdate {
	mtu.mutation.Where(ps...)
	return mtu
}

// SetUpdatedAt sets the "updated_at" field.
func (mtu *MessageTypeUpdate) SetUpdatedAt(t time.Time) *MessageTypeUpdate {
	mtu.mutation.SetUpdatedAt(t)
	return mtu
}

// SetMessageType sets the "message_type" field.
func (mtu *MessageTypeUpdate) SetMessageType(s string) *MessageTypeUpdate {
	mtu.mutation.SetMessageType(s)
	return mtu
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (mtu *MessageTypeUpdate) SetNillableMessageType(s *string) *MessageTypeUpdate {
	if s != nil {
		mtu.SetMessageType(*s)
	}
	return mtu
}

// Mutation returns the MessageTypeMutation object of the builder.
func (mtu *MessageTypeUpdate) Mutation() *MessageTypeMutation {
	return mtu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mtu *MessageTypeUpdate) Save(ctx context.Context) (int, error) {
	mtu.defaults()
	return withHooks(ctx, mtu.sqlSave, mtu.mutation, mtu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtu *MessageTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := mtu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mtu *MessageTypeUpdate) Exec(ctx context.Context) error {
	_, err := mtu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtu *MessageTypeUpdate) ExecX(ctx context.Context) {
	if err := mtu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mtu *MessageTypeUpdate) defaults() {
	if _, ok := mtu.mutation.UpdatedAt(); !ok {
		v := messagetype.UpdateDefaultUpdatedAt()
		mtu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtu *MessageTypeUpdate) check() error {
	if v, ok := mtu.mutation.MessageType(); ok {
		if err := messagetype.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "MessageType.message_type": %w`, err)}
		}
	}
	return nil
}

func (mtu *MessageTypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mtu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagetype.Table, messagetype.Columns, sqlgraph.NewFieldSpec(messagetype.FieldID, field.TypeInt))
	if ps := mtu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtu.mutation.UpdatedAt(); ok {
		_spec.SetField(messagetype.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mtu.mutation.MessageType(); ok {
		_spec.SetField(messagetype.FieldMessageType, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mtu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mtu.mutation.done = true
	return n, nil
}

// MessageTypeUpdateOne is the builder for updating a single MessageType entity.
type MessageTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageTypeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (mtuo *MessageTypeUpdateOne) SetUpdatedAt(t time.Time) *MessageTypeUpdateOne {
	mtuo.mutation.SetUpdatedAt(t)
	return mtuo
}

// SetMessageType sets the "message_type" field.
func (mtuo *MessageTypeUpdateOne) SetMessageType(s string) *MessageTypeUpdateOne {
	mtuo.mutation.SetMessageType(s)
	return mtuo
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (mtuo *MessageTypeUpdateOne) SetNillableMessageType(s *string) *MessageTypeUpdateOne {
	if s != nil {
		mtuo.SetMessageType(*s)
	}
	return mtuo
}

// Mutation returns the MessageTypeMutation object of the builder.
func (mtuo *MessageTypeUpdateOne) Mutation() *MessageTypeMutation {
	return mtuo.mutation
}

// Where appends a list predicates to the MessageTypeUpdate builder.
func (mtuo *MessageTypeUpdateOne) Where(ps ...predicate.MessageType) *MessageTypeUpdateOne {
	mtuo.mutation.Where(ps...)
	return mtuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mtuo *MessageTypeUpdateOne) Select(field string, fields ...string) *MessageTypeUpdateOne {
	mtuo.fields = append([]string{field}, fields...)
	return mtuo
}

// Save executes the query and returns the updated MessageType entity.
func (mtuo *MessageTypeUpdateOne) Save(ctx context.Context) (*MessageType, error) {
	mtuo.defaults()
	return withHooks(ctx, mtuo.sqlSave, mtuo.mutation, mtuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mtuo *MessageTypeUpdateOne) SaveX(ctx context.Context) *MessageType {
	node, err := mtuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mtuo *MessageTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := mtuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mtuo *MessageTypeUpdateOne) ExecX(ctx context.Context) {
	if err := mtuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mtuo *MessageTypeUpdateOne) defaults() {
	if _, ok := mtuo.mutation.UpdatedAt(); !ok {
		v := messagetype.UpdateDefaultUpdatedAt()
		mtuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mtuo *MessageTypeUpdateOne) check() error {
	if v, ok := mtuo.mutation.MessageType(); ok {
		if err := messagetype.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "MessageType.message_type": %w`, err)}
		}
	}
	return nil
}

func (mtuo *MessageTypeUpdateOne) sqlSave(ctx context.Context) (_node *MessageType, err error) {
	if err := mtuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagetype.Table, messagetype.Columns, sqlgraph.NewFieldSpec(messagetype.FieldID, field.TypeInt))
	id, ok := mtuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mtuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagetype.FieldID)
		for _, f := range fields {
			if !messagetype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messagetype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mtuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mtuo.mutation.UpdatedAt(); ok {
		_spec.SetField(messagetype.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := mtuo.mutation.MessageType(); ok {
		_spec.SetField(messagetype.FieldMessageType, field.TypeString, value)
	}
	_node = &MessageType{config: mtuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mtuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagetype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mtuo.mutation.done = true
	return _node, nil
}
