// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thaiha1607/foursquare_server/ent/producttype"
)

// ProductTypeCreate is the builder for creating a ProductType entity.
type ProductTypeCreate struct {
	config
	mutation *ProductTypeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ptc *ProductTypeCreate) SetCreatedAt(t time.Time) *ProductTypeCreate {
	ptc.mutation.SetCreatedAt(t)
	return ptc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ptc *ProductTypeCreate) SetNillableCreatedAt(t *time.Time) *ProductTypeCreate {
	if t != nil {
		ptc.SetCreatedAt(*t)
	}
	return ptc
}

// SetUpdatedAt sets the "updated_at" field.
func (ptc *ProductTypeCreate) SetUpdatedAt(t time.Time) *ProductTypeCreate {
	ptc.mutation.SetUpdatedAt(t)
	return ptc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ptc *ProductTypeCreate) SetNillableUpdatedAt(t *time.Time) *ProductTypeCreate {
	if t != nil {
		ptc.SetUpdatedAt(*t)
	}
	return ptc
}

// SetProductType sets the "product_type" field.
func (ptc *ProductTypeCreate) SetProductType(s string) *ProductTypeCreate {
	ptc.mutation.SetProductType(s)
	return ptc
}

// Mutation returns the ProductTypeMutation object of the builder.
func (ptc *ProductTypeCreate) Mutation() *ProductTypeMutation {
	return ptc.mutation
}

// Save creates the ProductType in the database.
func (ptc *ProductTypeCreate) Save(ctx context.Context) (*ProductType, error) {
	ptc.defaults()
	return withHooks(ctx, ptc.sqlSave, ptc.mutation, ptc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ptc *ProductTypeCreate) SaveX(ctx context.Context) *ProductType {
	v, err := ptc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptc *ProductTypeCreate) Exec(ctx context.Context) error {
	_, err := ptc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptc *ProductTypeCreate) ExecX(ctx context.Context) {
	if err := ptc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ptc *ProductTypeCreate) defaults() {
	if _, ok := ptc.mutation.CreatedAt(); !ok {
		v := producttype.DefaultCreatedAt()
		ptc.mutation.SetCreatedAt(v)
	}
	if _, ok := ptc.mutation.UpdatedAt(); !ok {
		v := producttype.DefaultUpdatedAt()
		ptc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ptc *ProductTypeCreate) check() error {
	if _, ok := ptc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProductType.created_at"`)}
	}
	if _, ok := ptc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProductType.updated_at"`)}
	}
	if _, ok := ptc.mutation.ProductType(); !ok {
		return &ValidationError{Name: "product_type", err: errors.New(`ent: missing required field "ProductType.product_type"`)}
	}
	if v, ok := ptc.mutation.ProductType(); ok {
		if err := producttype.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "ProductType.product_type": %w`, err)}
		}
	}
	return nil
}

func (ptc *ProductTypeCreate) sqlSave(ctx context.Context) (*ProductType, error) {
	if err := ptc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ptc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ptc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ptc.mutation.id = &_node.ID
	ptc.mutation.done = true
	return _node, nil
}

func (ptc *ProductTypeCreate) createSpec() (*ProductType, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductType{config: ptc.config}
		_spec = sqlgraph.NewCreateSpec(producttype.Table, sqlgraph.NewFieldSpec(producttype.FieldID, field.TypeInt))
	)
	if value, ok := ptc.mutation.CreatedAt(); ok {
		_spec.SetField(producttype.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ptc.mutation.UpdatedAt(); ok {
		_spec.SetField(producttype.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ptc.mutation.ProductType(); ok {
		_spec.SetField(producttype.FieldProductType, field.TypeString, value)
		_node.ProductType = value
	}
	return _node, _spec
}

// ProductTypeCreateBulk is the builder for creating many ProductType entities in bulk.
type ProductTypeCreateBulk struct {
	config
	err      error
	builders []*ProductTypeCreate
}

// Save creates the ProductType entities in the database.
func (ptcb *ProductTypeCreateBulk) Save(ctx context.Context) ([]*ProductType, error) {
	if ptcb.err != nil {
		return nil, ptcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ptcb.builders))
	nodes := make([]*ProductType, len(ptcb.builders))
	mutators := make([]Mutator, len(ptcb.builders))
	for i := range ptcb.builders {
		func(i int, root context.Context) {
			builder := ptcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ptcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ptcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ptcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ptcb *ProductTypeCreateBulk) SaveX(ctx context.Context) []*ProductType {
	v, err := ptcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ptcb *ProductTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := ptcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ptcb *ProductTypeCreateBulk) ExecX(ctx context.Context) {
	if err := ptcb.Exec(ctx); err != nil {
		panic(err)
	}
}
