// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
	"github.com/thaiha1607/foursquare_server/ent/shipmentitem"
)

// ShipmentItemDelete is the builder for deleting a ShipmentItem entity.
type ShipmentItemDelete struct {
	config
	hooks    []Hook
	mutation *ShipmentItemMutation
}

// Where appends a list predicates to the ShipmentItemDelete builder.
func (sid *ShipmentItemDelete) Where(ps ...predicate.ShipmentItem) *ShipmentItemDelete {
	sid.mutation.Where(ps...)
	return sid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sid *ShipmentItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sid.sqlExec, sid.mutation, sid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sid *ShipmentItemDelete) ExecX(ctx context.Context) int {
	n, err := sid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sid *ShipmentItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shipmentitem.Table, sqlgraph.NewFieldSpec(shipmentitem.FieldID, field.TypeUUID))
	if ps := sid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sid.mutation.done = true
	return affected, err
}

// ShipmentItemDeleteOne is the builder for deleting a single ShipmentItem entity.
type ShipmentItemDeleteOne struct {
	sid *ShipmentItemDelete
}

// Where appends a list predicates to the ShipmentItemDelete builder.
func (sido *ShipmentItemDeleteOne) Where(ps ...predicate.ShipmentItem) *ShipmentItemDeleteOne {
	sido.sid.mutation.Where(ps...)
	return sido
}

// Exec executes the deletion query.
func (sido *ShipmentItemDeleteOne) Exec(ctx context.Context) error {
	n, err := sido.sid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shipmentitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sido *ShipmentItemDeleteOne) ExecX(ctx context.Context) {
	if err := sido.Exec(ctx); err != nil {
		panic(err)
	}
}
