// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/thaiha1607/foursquare_server/ent/shipmentstatuscode"
)

// ShipmentStatusCode is the model entity for the ShipmentStatusCode schema.
type ShipmentStatusCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// ShipmentStatus holds the value of the "shipment_status" field.
	ShipmentStatus string `json:"shipment_status,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShipmentStatusCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shipmentstatuscode.FieldID:
			values[i] = new(sql.NullInt64)
		case shipmentstatuscode.FieldShipmentStatus:
			values[i] = new(sql.NullString)
		case shipmentstatuscode.FieldCreatedAt, shipmentstatuscode.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShipmentStatusCode fields.
func (ssc *ShipmentStatusCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shipmentstatuscode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ssc.ID = int(value.Int64)
		case shipmentstatuscode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ssc.CreatedAt = new(time.Time)
				*ssc.CreatedAt = value.Time
			}
		case shipmentstatuscode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ssc.UpdatedAt = new(time.Time)
				*ssc.UpdatedAt = value.Time
			}
		case shipmentstatuscode.FieldShipmentStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shipment_status", values[i])
			} else if value.Valid {
				ssc.ShipmentStatus = value.String
			}
		default:
			ssc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShipmentStatusCode.
// This includes values selected through modifiers, order, etc.
func (ssc *ShipmentStatusCode) Value(name string) (ent.Value, error) {
	return ssc.selectValues.Get(name)
}

// Update returns a builder for updating this ShipmentStatusCode.
// Note that you need to call ShipmentStatusCode.Unwrap() before calling this method if this ShipmentStatusCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (ssc *ShipmentStatusCode) Update() *ShipmentStatusCodeUpdateOne {
	return NewShipmentStatusCodeClient(ssc.config).UpdateOne(ssc)
}

// Unwrap unwraps the ShipmentStatusCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ssc *ShipmentStatusCode) Unwrap() *ShipmentStatusCode {
	_tx, ok := ssc.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShipmentStatusCode is not a transactional entity")
	}
	ssc.config.driver = _tx.drv
	return ssc
}

// String implements the fmt.Stringer.
func (ssc *ShipmentStatusCode) String() string {
	var builder strings.Builder
	builder.WriteString("ShipmentStatusCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ssc.ID))
	if v := ssc.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ssc.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("shipment_status=")
	builder.WriteString(ssc.ShipmentStatus)
	builder.WriteByte(')')
	return builder.String()
}

// ShipmentStatusCodes is a parsable slice of ShipmentStatusCode.
type ShipmentStatusCodes []*ShipmentStatusCode
