// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
	"github.com/thaiha1607/foursquare_server/ent/warehouseassignment"
)

// WarehouseAssignmentDelete is the builder for deleting a WarehouseAssignment entity.
type WarehouseAssignmentDelete struct {
	config
	hooks    []Hook
	mutation *WarehouseAssignmentMutation
}

// Where appends a list predicates to the WarehouseAssignmentDelete builder.
func (wad *WarehouseAssignmentDelete) Where(ps ...predicate.WarehouseAssignment) *WarehouseAssignmentDelete {
	wad.mutation.Where(ps...)
	return wad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wad *WarehouseAssignmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wad.sqlExec, wad.mutation, wad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wad *WarehouseAssignmentDelete) ExecX(ctx context.Context) int {
	n, err := wad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wad *WarehouseAssignmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(warehouseassignment.Table, sqlgraph.NewFieldSpec(warehouseassignment.FieldID, field.TypeUUID))
	if ps := wad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wad.mutation.done = true
	return affected, err
}

// WarehouseAssignmentDeleteOne is the builder for deleting a single WarehouseAssignment entity.
type WarehouseAssignmentDeleteOne struct {
	wad *WarehouseAssignmentDelete
}

// Where appends a list predicates to the WarehouseAssignmentDelete builder.
func (wado *WarehouseAssignmentDeleteOne) Where(ps ...predicate.WarehouseAssignment) *WarehouseAssignmentDeleteOne {
	wado.wad.mutation.Where(ps...)
	return wado
}

// Exec executes the deletion query.
func (wado *WarehouseAssignmentDeleteOne) Exec(ctx context.Context) error {
	n, err := wado.wad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{warehouseassignment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wado *WarehouseAssignmentDeleteOne) ExecX(ctx context.Context) {
	if err := wado.Exec(ctx); err != nil {
		panic(err)
	}
}
