// Code generated by ent, DO NOT EDIT.

package invoicestatuscode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/thaiha1607/foursquare_server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// InvoiceStatus applies equality check predicate on the "invoice_status" field. It's identical to InvoiceStatusEQ.
func InvoiceStatus(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldInvoiceStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// InvoiceStatusEQ applies the EQ predicate on the "invoice_status" field.
func InvoiceStatusEQ(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEQ(FieldInvoiceStatus, v))
}

// InvoiceStatusNEQ applies the NEQ predicate on the "invoice_status" field.
func InvoiceStatusNEQ(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNEQ(FieldInvoiceStatus, v))
}

// InvoiceStatusIn applies the In predicate on the "invoice_status" field.
func InvoiceStatusIn(vs ...string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldIn(FieldInvoiceStatus, vs...))
}

// InvoiceStatusNotIn applies the NotIn predicate on the "invoice_status" field.
func InvoiceStatusNotIn(vs ...string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldNotIn(FieldInvoiceStatus, vs...))
}

// InvoiceStatusGT applies the GT predicate on the "invoice_status" field.
func InvoiceStatusGT(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGT(FieldInvoiceStatus, v))
}

// InvoiceStatusGTE applies the GTE predicate on the "invoice_status" field.
func InvoiceStatusGTE(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldGTE(FieldInvoiceStatus, v))
}

// InvoiceStatusLT applies the LT predicate on the "invoice_status" field.
func InvoiceStatusLT(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLT(FieldInvoiceStatus, v))
}

// InvoiceStatusLTE applies the LTE predicate on the "invoice_status" field.
func InvoiceStatusLTE(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldLTE(FieldInvoiceStatus, v))
}

// InvoiceStatusContains applies the Contains predicate on the "invoice_status" field.
func InvoiceStatusContains(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldContains(FieldInvoiceStatus, v))
}

// InvoiceStatusHasPrefix applies the HasPrefix predicate on the "invoice_status" field.
func InvoiceStatusHasPrefix(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldHasPrefix(FieldInvoiceStatus, v))
}

// InvoiceStatusHasSuffix applies the HasSuffix predicate on the "invoice_status" field.
func InvoiceStatusHasSuffix(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldHasSuffix(FieldInvoiceStatus, v))
}

// InvoiceStatusEqualFold applies the EqualFold predicate on the "invoice_status" field.
func InvoiceStatusEqualFold(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldEqualFold(FieldInvoiceStatus, v))
}

// InvoiceStatusContainsFold applies the ContainsFold predicate on the "invoice_status" field.
func InvoiceStatusContainsFold(v string) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.FieldContainsFold(FieldInvoiceStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceStatusCode) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceStatusCode) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceStatusCode) predicate.InvoiceStatusCode {
	return predicate.InvoiceStatusCode(sql.NotPredicates(p))
}
