name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          min-go-version: 1.21
