name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Fetch dependencies
        run: go mod download && go mod verify
      - name: Check code formatting
        run: test -z $(gofmt -s -l .)
      - name: Run go vet
        run: go vet
      - name: Check generated files
        run: bash ./misc/check_ent_files.sh
